---

redis_module: '@redis:{{redis_version}}'
redis_port: 6379
redis_bind_interface: "127.0.0.1 ::1 {{ansible_default_ipv4.address}}"

redis_data_dir: /app/redis/data
redis_log_dir: /app/redis/logs/
redis_dirs:
  - '{{ redis_data_dir }}'
  - '{{ redis_log_dir }}'